# Generated by Django 5.2.1 on 2025-05-24 00:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('total_plants', models.IntegerField(help_text='Total number of mango plants on the property', validators=[django.core.validators.MinValueValidator(1)])),
                ('farm_size', models.DecimalField(decimal_places=2, help_text='Farm size in hectares', max_digits=10)),
                ('stocking_rate', models.DecimalField(decimal_places=2, editable=False, help_text='Plants per hectare', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('reference_pest_id', models.IntegerField(blank=True, help_text='ID from reference pest database if identified', null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlantLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., North Block, Section A', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Additional location details')),
                ('number_of_plants', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='App2.farm')),
            ],
            options={
                'unique_together': {('farm', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Surveillance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_observed', models.DateField()),
                ('time_observed', models.TimeField()),
                ('plants_inspected', models.IntegerField(help_text='Number of plants inspected in this surveillance', validators=[django.core.validators.MinValueValidator(1)])),
                ('plant_part', models.CharField(choices=[('leaves', 'Leaves'), ('fruit', 'Fruit'), ('flowers', 'Flowers'), ('stem', 'Stem/Branches'), ('roots', 'Roots'), ('whole', 'Whole Plant')], max_length=20)),
                ('severity', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')])),
                ('pest_count', models.IntegerField(default=0, help_text='Estimated number of pests found')),
                ('notes', models.TextField(blank=True)),
                ('weather_conditions', models.CharField(blank=True, help_text='e.g., Sunny, Rainy, Humid', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveillance_records', to='App2.farm')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveillance_records', to='App2.plantlocation')),
                ('pest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='App2.pest')),
            ],
            options={
                'ordering': ['-date_observed', '-time_observed'],
            },
        ),
    ]
