# Generated by Django 5.2.1 on 2025-05-27 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveillance',
            name='location',
        ),
        migrations.DeleteModel(
            name='PlantLocation',
        ),
    ]
