# Generated by Django 5.2 on 2025-05-18 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveillance',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='surveillance',
            name='pest',
        ),
        migrations.DeleteModel(
            name='Farm',
        ),
        migrations.DeleteModel(
            name='Pest',
        ),
        migrations.DeleteModel(
            name='Surveillance',
        ),
    ]
